.TH "OVOPLAYER" "1" "1.2.0" "Marco Caselli" "Audio"
.SH "NAME"
ovoplayer \- A free music player written in lazarus
.SH "SYNTAX"
.LP 
ovoplayer [\fIoption\fP] <\fIfilename\fP>
.SH "DESCRIPTION"
.LP 
A free Music player
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "AUTHORS"
.LP 
Marco Caselli<marcocas@gmail.com>
